[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
name = "webgoopy"
version = "0.1.0"
readme = "README.md"

[project.license]
text = "proprietary"

[project.urls]
Homepage = "https://github.com/pyrym/webgoopy"

[tool.setuptools]
include-package-data = true
packages = [
   "webgoo",
]

[tool.ruff]
target-version = "py311"
# See https://github.com/charliermarsh/ruff#rules for error code definitions.
select = [
    # "ANN", # annotations
    "B", # bugbear
    "C", # comprehensions
    "E", # style errors
    "F", # flakes
    "I", # import sorting
    "RUF100", # meta
    "U", # upgrade
    "W", # style warnings
    "YTT", # sys.version
]
ignore = [
  "C901", # Comprehension is too complex (11 > 10)
  "N802", # Function name should be lowercase
  "N806", # Variable in function should be lowercase
  "E501", # Line too long ({width} > {limit} characters)
  "B904", # raise ... from err
  "B905", # zip() without an explicit strict= parameter
  "ANN101", # type hint for `self`
  "ANN002", # type hint for *args
  "ANN003", # type hint for **kwargs
  "UP007", # uses `|` instead of `Optional`
    "UP038", # uses `|` instead of `tuple`	
]
line-length = 90
