name: Build Wheels

on: 
  pull_request: {}

jobs:
  wheels:
    name: Check Wheels On Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Python deps
        run: |
          python -m pip install cffi ruff numpy glfw imgui trimesh pillow
      - name: Run Codegen and build extension
        run: |
          python codegen/fetch_wgpu_bins.py
          bun codegen/generate.ts
          cd xgpu && python _build_ext.py
      - name: Run Tests
        run: |
          sudo apt install -y libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers
          python -m pip install .
          cd examples/tests && python run_tests.py
      - name: Build Wheels
        run: |
          python -m pip install cibuildwheel==2.21.3
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
