name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Run Codegen
        run: |
          make build

      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.16.2
        with:
          package-dir: ./build

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl