name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Run Codegen (Pyry's Docker-free version)
        run: |
          python -m pip install ruff
          python -m pip install cffi
          bun codegen/fetch_wgpu_bins.ts
          bun codegen/generate.ts
          cd webgoo
          python _build_ext.py

      - name: Build Wheels
        run: |
          python -m pip install cibuildwheel==2.16.2
          cd webgoo
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./build/wheelhouse/*.whl