name: Build Wheels

on: 
  push:
    branches: main
  pull_request: {}

jobs:
  codegen:
    name: Run Codegen
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Run Codegen
        run: |
          bun codegen/fetch_wgpu_bins.ts
          bun codegen/generate.ts
          python -m pip install cffi
          cd webgoo
          python _build_ext.py

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: codegen
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Download binaries
        run: |
          python -m pip install ruff requests
          python codegen/fetch_wgpu_bins.py

      - name: Build Wheels
        run: |
          python -m pip install cibuildwheel==2.16.2
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl